# ============================================================================
# 11_organize_figures.R — Create multi-panel combined figures and organize
#                          into main_text/ and SI/ directories
#
# Creates combined multi-panel figures using magick, then copies all
# figures into figures/main_text/ and figures/SI/ for manuscript review.
# ============================================================================

library(magick)

fig_dir <- "figures"
src_dir <- file.path(fig_dir, "archive")  # individual panels live here
main_dir <- file.path(fig_dir, "main_text")
si_dir   <- file.path(fig_dir, "SI")

# Clean output directories
unlink(main_dir, recursive = TRUE)
unlink(si_dir, recursive = TRUE)
dir.create(main_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(si_dir,   recursive = TRUE, showWarnings = FALSE)

# Helper: read and resize to common height (for side-by-side)
combine_horizontal <- function(file_a, file_b, output, target_height = 1200) {
  a <- image_read(file.path(src_dir, file_a))
  b <- image_read(file.path(src_dir, file_b))
  a <- image_scale(a, paste0("x", target_height))
  b <- image_scale(b, paste0("x", target_height))
  a <- image_annotate(a, "(a)", size = 40, gravity = "northwest",
                      location = "+10+10", font = "Helvetica",
                      weight = 700, color = "black")
  b <- image_annotate(b, "(b)", size = 40, gravity = "northwest",
                      location = "+10+10", font = "Helvetica",
                      weight = 700, color = "black")
  combined <- image_append(c(a, b), stack = FALSE)
  image_write(combined, file.path(main_dir, output), density = 300)
  message("  Created: ", output)
}

# Helper: stack vertically (for stem + soil comparisons)
combine_vertical <- function(file_a, file_b, output, target_width = 2400) {
  a <- image_read(file.path(src_dir, file_a))
  b <- image_read(file.path(src_dir, file_b))
  a <- image_scale(a, paste0(target_width, "x"))
  b <- image_scale(b, paste0(target_width, "x"))
  a <- image_annotate(a, "(a)", size = 40, gravity = "northwest",
                      location = "+10+10", font = "Helvetica",
                      weight = 700, color = "black")
  b <- image_annotate(b, "(b)", size = 40, gravity = "northwest",
                      location = "+10+10", font = "Helvetica",
                      weight = 700, color = "black")
  combined <- image_append(c(a, b), stack = TRUE)
  image_write(combined, file.path(main_dir, output), density = 300)
  message("  Created: ", output)
}

# Helper: 2x2 grid (for 4-panel detection limits overview)
combine_2x2 <- function(files, labels, output, target_w = 1200, target_h = 900) {
  imgs <- lapply(files, function(f) image_read(file.path(src_dir, f)))
  imgs <- lapply(imgs, function(img) image_scale(img, paste0(target_w, "x", target_h, "!")))
  for (i in seq_along(imgs)) {
    imgs[[i]] <- image_annotate(imgs[[i]], labels[i], size = 36,
                                gravity = "northwest", location = "+10+10",
                                font = "Helvetica", weight = 700, color = "black")
  }
  top_row    <- image_append(c(imgs[[1]], imgs[[2]]), stack = FALSE)
  bottom_row <- image_append(c(imgs[[3]], imgs[[4]]), stack = FALSE)
  combined   <- image_append(c(top_row, bottom_row), stack = TRUE)
  image_write(combined, file.path(main_dir, output), density = 300)
  message("  Created: ", output)
}

# ============================================================================
# CREATE COMBINED FIGURES
# ============================================================================

message("\n=== Creating combined multi-panel figures ===")

# Fig 1: Detection limits overview (2x2)
# (a) precision bar chart, (b) Allan violin, (c) MDF vs duration, (d) detection rates
# Note: Fig 2 = SE vs MDF (standalone, not generated here)
# Note: Fig 3 = CO2 validity examples (standalone, generated by script 15)
combine_2x2(
  files  = c("precision_comparison_CH4.png",
             "ch4_allan_deviation_by_instrument.png",
             "mdf_vs_duration.png",
             "mdf_detection_rates_stem.png"),
  labels = c("(a)", "(b)", "(c)", "(d)"),
  output = "fig01_detection_limits_overview.png"
)

# Fig 4: R2 vs flux — stem + soil (stacked)
combine_vertical(
  "r2_vs_flux_by_temperature.png",
  "soil_r2_vs_flux_by_temperature.png",
  "fig04_r2_vs_flux_stem_soil.png"
)

# Fig 5: Seasonal/temperature exclusion — 2x2 grid
# (a) stem by season, (b) stem by temp bin, (c) soil by season, (d) soil by temp bin
combine_2x2(
  files  = c("seasonal_fraction_flagged.png",
             "temp_bin_fraction_flagged.png",
             "soil_seasonal_fraction_flagged.png",
             "soil_temp_bin_fraction_flagged.png"),
  labels = c("(a)", "(b)", "(c)", "(d)"),
  output = "fig05_seasonal_exclusion_stem_soil.png"
)

# Fig 6: Treatment effects (ridgelines + bias dot-line)
combine_horizontal(
  "ch4_mdf_treatment_ridges.png",
  "ch4_mdf_treatment_bias.png",
  "fig06_treatment_effects.png",
  target_height = 1800
)

# Fig 7: Cumulative budget — stem + soil (stacked)
combine_vertical(
  "cumulative_annual_budget.png",
  "soil_cumulative_annual_budget.png",
  "fig07_cumulative_budget_stem_soil.png"
)

# ============================================================================
# CREATE COMBINED TRANSFORMATION FIGURE
# ============================================================================

message("\n=== Creating combined transformation figure ===")

# Fig 8: Transformation comparison + arcsinh behavior (stacked)
combine_vertical(
  "ch4_transform_comparison.png",
  "arcsinh_behavior.png",
  "fig08_transformation_overview.png"
)

# ============================================================================
# COPY SI FIGURES
# ============================================================================

message("\n=== Copying SI figures ===")

si_figures <- c(
  "figS01_flux_ridges_by_filter.png"        = "ch4_flux_ridges_by_filter.png",
  "figS02_flux_ridges_by_instrument.png"    = "ch4_flux_ridges_by_instrument.png",
  "figS03_flux_density_by_instrument.png"   = "ch4_flux_density_by_instrument.png",
  "figS04_pct_negative_by_month.png"        = "ch4_pct_negative_by_month_instrument.png",
  "figS05_monthly_flux_by_instrument.png"   = "ch4_flux_monthly_by_instrument.png",
  "figS06_monthly_timeseries_noise.png"     = "ch4_flux_monthly_timeseries_noise.png",
  "figS07_treatment_pct_change.png"         = "ch4_mdf_treatment_pct_change.png",
  "figS08_precision_CO2.png"                = "precision_comparison_CO2.png",
  "figS09_rolling_window_LGR3_CH4.png"     = "rolling_window_LGR3_CH4.png",
  "figS10_rolling_window_LGR3_CO2.png"     = "rolling_window_LGR3_CO2.png",
  "figS11_rolling_window_YMF_CH4.png"      = "rolling_window_YMF_CH4.png",
  "figS12_rolling_window_YMF_CO2.png"      = "rolling_window_YMF_CO2.png",
  "figS13_allan_deviation_CH4.png"          = "allan_deviation_CH4.png",
  "figS14_allan_deviation_CO2.png"          = "allan_deviation_CO2.png",
  "figS15_mdf_detection_rates_all.png"      = "mdf_detection_rates_all.png",
  "figS16_mdf_threshold_distributions.png"  = "mdf_threshold_distributions.png",
  "figS17_r2_vs_flux_signed_stem.png"       = "r2_vs_flux_signed_by_temperature.png",
  "figS18_r2_vs_flux_signed_soil.png"       = "soil_r2_vs_flux_signed_by_temperature.png",
  "figS19_r2_vs_flux_linear_stem.png"       = "r2_vs_flux_linear_by_temperature.png",
  "figS20_r2_vs_flux_linear_soil.png"       = "soil_r2_vs_flux_linear_by_temperature.png",
  "figS21_timeseries_filter_stem.png"       = "timeseries_filter_status.png",
  "figS22_flux_vs_temp_stem.png"            = "flux_vs_temperature_filter_status.png",
  "figS23_timeseries_filter_soil.png"       = "soil_timeseries_filter_status.png",
  "figS24_flux_vs_temp_soil.png"            = "soil_flux_vs_temperature_filter_status.png",
  "figS25_treatment_by_instrument.png"      = "ch4_mdf_treatment_by_instrument.png",
  "figS26_qq_plots.png"                     = "ch4_transform_qq.png",
  "figS27_flux_vs_noise_floor.png"          = "ch4_flux_vs_noise_floor.png"
)

for (dest_name in names(si_figures)) {
  src <- file.path(src_dir, si_figures[dest_name])
  dst <- file.path(si_dir, dest_name)
  if (file.exists(src)) {
    file.copy(src, dst, overwrite = TRUE)
    message("  Copied: ", dest_name)
  } else {
    message("  WARNING: source not found: ", si_figures[dest_name])
  }
}

# ============================================================================
# SUMMARY
# ============================================================================

n_main <- length(list.files(main_dir, pattern = "\\.png$"))
n_si   <- length(list.files(si_dir, pattern = "\\.png$"))

message("\n=== Figure organization complete ===")
message("  Main text: ", n_main, " figures in figures/main_text/")
message("  SI:        ", n_si,   " figures in figures/SI/")
message("\nMain text figures:")
cat(paste0("  ", sort(list.files(main_dir, pattern = "\\.png$")), collapse = "\n"), "\n")
message("\nSI figures:")
cat(paste0("  ", sort(list.files(si_dir, pattern = "\\.png$")), collapse = "\n"), "\n")
